name: github-greetings

on:
 workflow_dispatch:
  inputs:
   name:
    description: 'person to great'
    default: 'world'
    required: true

jobs:
  greet:
    runs-on: windows-latest
    steps:
    - name: send greetings
      run: echo "Hello ${{github.event.inputs.name}}"
