name: github-greetings

on:
 workflow_dispatch:
  inputs:
   name:
    description: 'person to great'
    default: 'world'
    required: true

jobs:
  greeting:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
